### ISSUE TITLE
Great Plugin! Not working in IE8?

### ISSUE THREAD

**Issue by gripmedia** [valtlfelipe/TinyMCE-LocalAutoSave#6]
Hi Felipe. Love your plugin. I notice it does not fire in IE8 is that correct? I can get it to load but it won't autosave? 

Client wants it to work in IE8. Compatibility says it should work?

Thanks! And how do we contribute money to your project?

-jerry chrisman  gripmedia jerrygithub@gripmedia.net

**Comment by valtlfelipe** [comment]
Hi @gripmedia ! Sorry again for the delay... could you please provide a working example, or some screenshots? It would be very helpful.

**Comment by valtlfelipe** [comment]
Fixed. Please update your files for latest version 0.4!
https://github.com/valtlfelipe/TinyMCE-LocalAutoSave/releases/tag/0.4
