### ISSUE TITLE
The Load menu is out of alignment?

### ISSUE THREAD

**Issue by MurdoD** [valtlfelipe/TinyMCE-LocalAutoSave#7]
Love this plugin, big help in my project. However, when you use it in FireFox, the character count is on a row below the save time/date...

**Comment by valtlfelipe** [comment]
Hi @MurdoD! Thank you!

I will do the possible to solve your problem, but i could not really understand what you mean. Could you please provide a working example, or a screenshot! It would be very helpful.

**Comment by valtlfelipe** [comment]
Fixed. Please update your files for latest version 0.4!
https://github.com/valtlfelipe/TinyMCE-LocalAutoSave/releases/tag/0.4
