### ISSUE TITLE
Local Date Time displayed

### ISSUE THREAD

**Issue by IreneLing** [valtlfelipe/TinyMCE-LocalAutoSave#9]
Hi,
Firstly, thanks a lot for this plugin which is really useful and easy to use.

Currently I have a small issue with the date time. My local time is GMT+8, however the time displayed in the menu is GMT+1, is it possible to have it match my local date time?

Thank you.

**Comment by IreneLing** [comment]
Sorry the time displayed in menu is GMT+0, I unable to edit the question due to my outdated browser, my apologize.

**Comment by valtlfelipe** [comment]
I will take a look into this, and will let you know as soon as possible.

Thank you for your submission.

**Comment by IreneLing** [comment]
Hi,

It's been a while. Hope you're doing fine.
Is there any updates regarding this case?

Thank you.

**Comment by valtlfelipe** [comment]
Hi! I'm really sorry for the delay.

I have already identified the problem and will fix it now.

**Comment by valtlfelipe** [comment]
Released [0.4.2](https://github.com/valtlfelipe/TinyMCE-LocalAutoSave/releases/tag/0.4.2) with this fix, please update.

**Comment by IreneLing** [comment]
Hi,

Sorry for delayed response.
Really thanks for the updates. Can't thank you enough for this useful plugin, I appreciate it.

**Comment by valtlfelipe** [comment]
You are welcome!!
Thanks, It makes me really happy that it helps others. =D
